name: Pytest control Predict and Database
on: push
jobs:
  qa:
    name: Check tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout on master
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: "3.x"

      - name: Install requirements
        run: |
          pip install -r $GITHUB_WORKSPACE/requirements.txt

      - name: Run tests database
        run: |
          pytest $GITHUB_WORKSPACE/test/database_test.py

      - name: Run tests predict
        run: |
          pytest $GITHUB_WORKSPACE/test/predict_test.py